# Data Cleaning using numpy
The following are the student marks of a class [44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,,122,92,np.nan,87,96,97,1,19,2,53, 44]

Find the no of outliers and missing values?
replace the outliers with 45 and missing value with 87.
what is the average marks of students after 2nd step?
How many students got less than 60 marks?
what is the maximum marks?
Convert the marks to float32.

In [2]:
import numpy as np

In [41]:
student_marks = np.array([44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,122,92,np.nan,87,96,97,1,19,2,53, 44])

In [42]:
np.isnan(student_marks)

array([False, False,  True, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False])

In [43]:
cond = student_marks[(student_marks > 100) | (student_marks < 0 )]
cond

array([188., 120., 122.])

In [44]:
len(cond)

3

In [45]:
missing = np.sum(np.isnan(student_marks))
missing

4

In [47]:
np.where(cond,45,student_marks).astype('int16')


ValueError: operands could not be broadcast together with shapes (3,) () (29,) 

In [46]:
b = np.where(np.isnan(student_marks),87,student_marks).astype('int16')
b

array([ 44,  24,  87,  59,  32,  96, 188,  52,  62,  58,  52, 120,  87,
        87,   3,  56,  81,  59, 122,  92,  87,  87,  96,  97,   1,  19,
         2,  53,  44], dtype=int16)

# Solving Linear Equations
2x + 3y - z = 10

x - y + 2z = 5

3x + 2y + z = 12

2x + y - z + 3w = 8

3x - 2y + 2z + 2w = 1

x + 3y - 2z + w = 7

4x - y + z - 2w = 3

4x + 2y - 3z = 10

-2x + 3y + z = -3

x - y + 2z = 4

Solve the system of equations using NumPy's linalg.solve function.

In [16]:
#2x + 3y - z = 10

#x - y + 2z = 5

#3x + 2y + z = 12

a = np.array([[2,3,-1],[1,-1,2],[3,2,1]])
b = np.array([10,5,12])

In [17]:
np.linalg.solve(a,b)

array([-6.75539944e+15,  6.75539944e+15,  6.75539944e+15])

In [4]:
c = np.array([[2,1,-1,3],[3,-2,2,2],[1,3,-2,1],[4,-1,1,-2]])
d = np.array([8,1,7,3])

In [5]:
np.linalg.solve(c,d)

array([ 1.73170732, -0.75609756, -3.46341463,  0.6097561 ])

In [7]:
e = np.array([[4,2,-3],[-2,3,1],[1,-1,2]])
f = np.array([10,-3,4])

In [8]:
np.linalg.solve(e,f)

array([2.85365854, 0.6097561 , 0.87804878])

# Conditional Selection with np.where()
Generate a random 1D array A of 10 integers between 1 and 100.

Use np.where() to find the indices where the elements of A are greater than 50.

Create a new array B that contains elements from A where the condition is met.

Calculate the mean of array B and print it along with arrays A and B.


In [13]:
i = np.random.randint(1,100,10)
i

array([33, 39, 99, 80, 91,  5, 54, 80, 58, 81])

In [16]:
a = i[np.where(i > 50)]
a

array([99, 80, 91, 54, 80, 58, 81])

In [18]:
B = np.array(a)
B

array([99, 80, 91, 54, 80, 58, 81])

77.57142857142857


In [24]:
print("array A as : ",i , "adn array B as : ",np.mean(a))

array A as :  [33 39 99 80 91  5 54 80 58 81] adn array B as :  77.57142857142857


# Replace Values with np.where()
Create a 4x4 random integer matrix C with values between -10 and 10.

Use np.where() to replace all negative values in matrix C with 0.

Print the original matrix C and the modified matrix

In [27]:
r1 = np.random.randint(-10,10,16)
r1

array([-1,  4,  1,  7, -2,  4, -4,  7, -7,  6,  3,  0,  7, -7,  2,  1])

In [28]:
r1.reshape(4,4)

array([[-1,  4,  1,  7],
       [-2,  4, -4,  7],
       [-7,  6,  3,  0],
       [ 7, -7,  2,  1]])

In [33]:
m = np.where(r1 < 0,0,r1)
m

array([0, 4, 1, 7, 0, 4, 0, 7, 0, 6, 3, 0, 7, 0, 2, 1])

In [32]:
print("original matrix : ",r1)

original matrix :  [-1  4  1  7 -2  4 -4  7 -7  6  3  0  7 -7  2  1]


In [34]:
print("modified matrix : ",m)

modified matrix :  [0 4 1 7 0 4 0 7 0 6 3 0 7 0 2 1]
