# Creation of ndarray

Write python code to create 3d array in different ways with 15 elements.
Array Creation:
a. Create a 4D NumPy array containing the first 12 positive integers as arr1. b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1. 3. Find all attributes of array1 and array2 4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.

# Array Slicing and Indexing:

a. Creating Arrays: - Create a 1-dimensional NumPy array arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29]. - Create a 2-dimensional NumPy array arr2 with the values [[0, 1, 2], [3, 4, 5], [6, 7, 8]].

b.Basic Indexing: - Print the element at index 3 of arr1. - Print the element at row 2, column 1 of arr2

c. Array Slicing: - Print the first five elements of arr1. - Print the subarray of arr2 consisting of the last two rows and the first two columns. - Print every second element starting from index 1 up to index 7 of arr1.

# Data Type Manipulation

a. Creating Arrays with Specific Data Types: - Create a 1-dimensional NumPy array int_array with the values [1, 2, 3, 4, 5] and the data type int16. - Create a 1-dimensional NumPy array float_array with the values [0.1, 0.2, 0.3, 0.4, 0.5] and the data type float64.

b. Data Type Conversion: - Convert the float_array to an array with data type int32. Print the result. - Convert the int_array to an array with data type float32. Print the result.
# Generating Random Numbers:

Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

Apply descriptive statistics for rand_matrix.

# Analyze the Data:

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

Describe the data using numpy array. Measure the following:

How many employees are getting more less than 50000?

Is it following Normal Distribution?

What is the median salary?

What is the range of salaries for this company?

Find the salaries between average salary and 75% of salaries?

How many employees are getting less than 25 % of salaries ?

In [2]:
import numpy as np

# Creation of ndarray
Write python code to create 3d array in different ways with 15 elements. Array Creation: a. Create a 4D NumPy array containing the first 12 positive integers as arr1. b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1. 3. Find all attributes of array1 and array2 4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.

In [3]:
 a1 = np.array([[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]]])

In [4]:
a1

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [6]:
b = np.array([[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]]],ndmin = 3)
b

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [8]:
b.reshape(5,3,1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [9]:
b.reshape(1,3,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [10]:
b.reshape(1,5,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]])

In [11]:
b.reshape(1,3,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [13]:
arr1 = np.array([[[[1,2,3,4,5,6,7,8,9,10,11,12]]]],ndmin = 4)
arr1

array([[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]]])

In [22]:
arr1.reshape(1,4,1,3)

array([[[[ 1,  2,  3]],

        [[ 4,  5,  6]],

        [[ 7,  8,  9]],

        [[10, 11, 12]]]])

In [23]:
arr1.reshape(4,3,1,1)

array([[[[ 1]],

        [[ 2]],

        [[ 3]]],


       [[[ 4]],

        [[ 5]],

        [[ 6]]],


       [[[ 7]],

        [[ 8]],

        [[ 9]]],


       [[[10]],

        [[11]],

        [[12]]]])

In [25]:
arr1 = np.arange(1,13).reshape(3,1,4,1)
arr1

array([[[[ 1],
         [ 2],
         [ 3],
         [ 4]]],


       [[[ 5],
         [ 6],
         [ 7],
         [ 8]]],


       [[[ 9],
         [10],
         [11],
         [12]]]])

In [33]:
n = np.random.rand(20).reshape(5,4,1)
n

array([[[0.99938931],
        [0.60709017],
        [0.75160537],
        [0.28055523]],

       [[0.08275678],
        [0.6423919 ],
        [0.99278291],
        [0.70676118]],

       [[0.10027075],
        [0.59260676],
        [0.82488317],
        [0.7690535 ]],

       [[0.5730457 ],
        [0.14237631],
        [0.17666744],
        [0.59521471]],

       [[0.38652922],
        [0.11755663],
        [0.80965293],
        [0.42584081]]])

In [30]:
m = np.linspace(0,1,20)
m

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [34]:
#attributes
arr1.ndim

4

In [36]:
arr1.nbytes

48

In [37]:
arr1.itemsize

4

In [38]:
arr1.size

12

In [39]:
arr1.dtype

dtype('int32')

In [42]:
arr1.nonzero()

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64))

In [43]:
b.nbytes

60

In [44]:
b.ndim

3

In [46]:
b.min()

1

In [47]:
b.size

15

In [48]:
b.itemsize

4

In [49]:
b.dtype

dtype('int32')

In [50]:
#measure and spread
np.mean(arr1)

6.5

In [51]:
np.median(arr1)

6.5

In [52]:
np.var(arr1)

11.916666666666666

In [53]:
np.std(arr1)

3.452052529534663

In [54]:
np.max(arr1)

12

In [55]:
np.min(arr1)

1

In [57]:
r1 = np.max(arr1) - np.min(arr1)
r1

11

In [58]:
q1 = np.percentile(arr1,25)
q1

3.75

In [59]:
q3 = np.percentile(arr1,75)
q3

9.25

In [60]:
IQR1 = q3 - q1
IQR1

5.5

In [61]:
ll = q1 - (1.5 * IQR1)
ll

-4.5

In [63]:
ul = q3 + (1.5 * IQR1)
ul

17.5

In [64]:
arr1[arr1>ul]

array([], dtype=int32)

In [65]:
arr1[arr1<ll]

array([], dtype=int32)

In [66]:
np.mean(b)

8.0

In [67]:
np.var(b)

18.666666666666668

In [68]:
np.std(b)

4.320493798938574

In [69]:
np.min(b)

1

In [70]:
np.max(b)

15

In [72]:
r2 = np.max(b) - np.min(b)
r2

14

# Array Slicing and Indexing:
a. Creating Arrays: - Create a 1-dimensional NumPy array arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29]. - Create a 2-dimensional NumPy array arr2 with the values [[0, 1, 2], [3, 4, 5], [6, 7, 8]].

b.Basic Indexing: - Print the element at index 3 of arr1. - Print the element at row 2, column 1 of arr2

c. Array Slicing: - Print the first five elements of arr1. - Print the subarray of arr2 consisting of the last two rows and the first two columns. - Print every second element starting from index 1 up to index 7 of arr1

In [76]:
#a
arr1 = np.array([0, 11, 26, 73, 42, 51, 6,77, 8,29],ndmin = 1)
arr1

array([ 0, 11, 26, 73, 42, 51,  6, 77,  8, 29])

In [78]:
arr2 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]],ndmin = 2)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
#b
arr1[3]

73

In [80]:

arr2[2][1]

7

In [81]:
#c
arr1[:5:]

array([ 0, 11, 26, 73, 42])

In [94]:
arr2[1:,0:2]

array([[3, 4],
       [6, 7]])

In [96]:
arr1[1:8:2]

array([11, 73, 51, 77])

# Generating Random Numbers:
Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

Apply descriptive statistics for rand_matrix.

In [99]:
rand_integers = np.random.randint(0,100,10)
rand_integers

array([84, 90, 48, 58,  8, 60, 10,  3, 31, 52])

In [101]:
rand_uniform = np.random.uniform(-1,1,5)
rand_uniform

array([ 0.89374301,  0.27855173,  0.1905256 , -0.77539995, -0.27701409])

In [104]:
rand_matrix = np.random.randint(50,100,16).reshape(4,4)
rand_matrix

array([[83, 91, 94, 63],
       [96, 72, 79, 50],
       [58, 86, 67, 65],
       [52, 82, 72, 75]])

In [105]:
np.mean( rand_matrix)

74.0625

In [106]:
np.median( rand_matrix)

73.5

In [107]:
np.var( rand_matrix)

191.43359375

In [108]:
np.std( rand_matrix)

13.835952939714705

In [111]:
np.max( rand_matrix)

96

In [110]:
np.min( rand_matrix)

50

In [113]:
r = np.max( rand_matrix) - np.min( rand_matrix)
r

46

In [114]:
q1 = np.percentile(rand_matrix,25)
q1

64.5

In [116]:
q3 = np.percentile(rand_matrix,75)
q3

83.75

In [118]:
IQR = q3 - q1
IQR

19.25

In [119]:
ll = q1 - (1.5*IQR)
ll

35.625

In [120]:
ul = q3 + (1.5*IQR)
ul

112.625

# Data Type Manipulation
a. Creating Arrays with Specific Data Types: - Create a 1-dimensional NumPy array int_array with the values [1, 2, 3, 4, 5] and the data type int16. - Create a 1-dimensional NumPy array float_array with the values [0.1, 0.2, 0.3, 0.4, 0.5] and the data type float64.

b. Data Type Conversion: - Convert the float_array to an array with data type int32. Print the result. - Convert the int_array to an array with data type float32. Print the result.

In [124]:
#a
int_array = np.array([1, 2, 3, 4, 5],dtype = "int16")
int_array

array([1, 2, 3, 4, 5], dtype=int16)

In [125]:
int_array.dtype

dtype('int16')

In [127]:
float_array = np.array([0.1, 0.2, 0.3, 0.4, 0.5],"float64")
float_array

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [128]:
float_array.dtype

dtype('float64')

In [129]:
#b
a = np.array([0.1, 0.2, 0.3, 0.4, 0.5],"int32")
a

array([0, 0, 0, 0, 0])

In [130]:
a.dtype

dtype('int32')

In [131]:
b = np.array([1, 2, 3, 4, 5],dtype = "float32")
b

array([1., 2., 3., 4., 5.], dtype=float32)

# Analyze the Data:
Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

Describe the data using numpy array. Measure the following:

How many employees are getting more less than 50000?

Is it following Normal Distribution?

What is the median salary?

What is the range of salaries for this company?

Find the salaries between average salary and 75% of salaries?

How many employees are getting less than 25 % of salaries ?

In [132]:
salaries = np.array([87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638])

In [133]:
salaries

array([  87877,   54494,   54804,   85051,   52453,   31250,   94868,
         66349,   39828,   60501,   58570,   74906,   41671,   51428,
         56414,   98446,   56819,   82833,   50477,   62898,   99658,
         89224,   34225,   79172,   32199,   63795,   90947,   55723,
         64557, 3113638])

In [134]:
salaries.nbytes

120

In [135]:
salaries.ndim

1

In [136]:
salaries.size

30

In [137]:
salaries.itemsize

4

In [156]:
m = np.mean(salaries)
m    

166169.16666666666

In [139]:
np.median(salaries)

61699.5

In [140]:
np.var(salaries)

299951833234.73895

In [141]:
np.std(salaries)

547678.585700353

In [142]:
r = np.max(salaries) - np.min(salaries)
r

3082388

In [144]:
q1 = np.percentile(salaries,25)
q1

52963.25

In [146]:
q3 = np.percentile(salaries,75)
q3

84496.5

In [147]:
IQR = q3 - q1
IQR

31533.25

In [148]:
l = q1 - (1.5*IQR)
l

5663.375

In [149]:
u = q3 + (1.5*IQR)
u

131796.375

In [157]:
p = salaries[salaries > u]
p

array([3113638])

In [151]:
salaries[salaries < l]

array([], dtype=int32)

In [154]:
c = salaries[salaries > 50000]
c

array([  87877,   54494,   54804,   85051,   52453,   94868,   66349,
         60501,   58570,   74906,   51428,   56414,   98446,   56819,
         82833,   50477,   62898,   99658,   89224,   79172,   63795,
         90947,   55723,   64557, 3113638])

In [155]:
len(c)

25

In [160]:
t = salaries[salaries <np.percentile(salaries,25)]
t

array([52453, 31250, 39828, 41671, 51428, 50477, 34225, 32199])

In [161]:
n = salaries[salaries > np.percentile(salaries,75)]
n

array([  87877,   85051,   94868,   98446,   99658,   89224,   90947,
       3113638])