# write a python code to create array in different ways

In [1]:
import numpy as np

In [4]:
a1 = np.array([5,9,78,1,2,36,4,0])
a1

array([ 5,  9, 78,  1,  2, 36,  4,  0])

In [8]:
np.zeros(4)

array([0., 0., 0., 0.])

In [9]:
np.ones(1)

array([1.])

In [10]:
np.dtype

numpy.dtype

In [11]:
len(a1)

8

In [22]:
l1 = [1,3,5,2,4,7,6,8,9]
np.array(l1)

array([1, 3, 5, 2, 4, 7, 6, 8, 9])

In [18]:
a1.itemsize

4

In [19]:
a1.ndim

1

In [20]:
a1.nbytes

32

In [21]:
np.arange(0,8,2)

array([0, 2, 4, 6])

In [23]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

# Array Creation:
a.create 1D numpy array containing the first 12 +ve no.s as arr1.
b.create a 1D numpy array1 with 20 elements containing integers b/w 0 and 12 using linspace.

In [2]:
arr1 = np.arange(1,13,1)

In [3]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
#b)
array1 = np.linspace(0,12,20)

In [5]:
array1

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

# find all attributes of array1 and array2 

In [31]:
arr1.nbytes

48

In [32]:
arr1.ndim

1

In [34]:
arr1.max()

12

In [35]:
arr1.min()

1

In [36]:
arr1.itemsize

4

In [37]:
arr1.size

12

In [38]:
arr1.dtype

dtype('int32')

In [39]:
array1.ndim

1

In [40]:
array1.nbytes

160

In [41]:
array1.size

20

In [42]:
array1.itemsize

8

In [43]:
array1.min()

0.0

In [44]:
array1.max()

12.0

# Apply measure and describethe data(attributes and descriptive statistics) to above arrays using Numpy

In [6]:
np.mean(arr1)

6.5

In [7]:
np.median(arr1)

6.5

In [8]:
np.max(arr1)

12

In [9]:
np.min(arr1)

1

In [11]:
r = np.max(arr1) - np.min(arr1)
r

11

In [14]:
np.var(arr1)

11.916666666666666

In [15]:
np.std(arr1)

3.452052529534663

In [17]:
q1 = np.percentile(arr1,25)
q1

3.75

In [19]:
q2 = np.percentile(arr1,50)
q2

6.5

In [20]:
q3 = np.percentile(arr1,75)
q3

9.25

In [22]:
IQR1 = q3 - q1
IQR1

5.5

In [24]:
lower = q1 - (1.5* IQR1)
lower

-4.5

In [25]:
upper = q3 + (1.5*IQR1)
upper

17.5

In [28]:
np.mean(array1)

5.999999999999999

In [29]:
np.median(array1)

6.0

In [30]:
np.max(array1)

12.0

In [31]:
np.min(array1)

0.0

In [33]:
r1 = np.max(array1) - np.min(array1)
r1

12.0

In [34]:
np.var(array1)

13.26315789473684

In [35]:
np.std(array1)

3.6418618720013036

In [38]:
q1 = np.percentile(array1,25)
q1

3.0

In [40]:
q2 = np.percentile(array1,50)
q2

6.0

In [42]:
q3 = np.percentile(array1,75)
q3

9.0

In [43]:
IQR2 = q3 - q1
IQR2

6.0

In [45]:
ll = q1 - (1.5*IQR2)
ll

-6.0

In [47]:
ul = q3 + (1.5*IQR2)
IQR2

6.0