# 
1. clean the data(outlier,missing values,type conversion)
2. What is the mean value of sepal length
3. sort the sepal width in ascending order.
4. apply all statistical measures on  sepal width and length
5. after cleaning the data ,save the file as 'cleaned_iris.txt' and load to jupyter again to display the values

In [2]:
import numpy as np

In [3]:
s2 = np.genfromtxt(r"C:\Users\chand\Downloads\Iris_clean_-_Copy.csv",dtype = 'float16',delimiter = ',')

In [4]:
s2

array([[      nan,       nan,       nan,       nan],
       [5.102e+00, 3.500e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.000e+00, 1.400e+00, 2.000e-01],
       [4.699e+00, 3.199e+00, 1.300e+00, 2.000e-01],
       [4.602e+00, 3.100e+00, 1.500e+00, 1.020e+01],
       [5.000e+01, 3.600e+00, 1.400e+00, 2.000e-01],
       [5.398e+00,       nan, 1.700e+00, 3.999e-01],
       [4.602e+00, 3.400e+00, 1.400e+00, 3.000e-01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01],
       [4.398e+00, 2.900e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.100e+00,       nan, 9.998e-02],
       [5.398e+00, 3.699e+00, 1.500e+00, 2.000e-01],
       [4.801e+00, 3.400e+00, 1.600e+00, 2.000e-01],
       [4.801e+00, 1.300e+02, 1.400e+00, 1.010e+01],
       [4.301e+00, 3.000e+00, 1.100e+00, 9.998e-02],
       [5.801e+00, 4.000e+00, 1.200e+00, 2.000e-01],
       [5.699e+00, 4.398e+00, 1.500e+00, 3.999e-01],
       [5.041e+01,       nan, 1.300e+00, 3.999e-01],
       [5.102e+00, 3.500e+00, 1.400e+00, 3.000

In [5]:
np.savetxt("iris.txt",s2)

In [6]:
np.loadtxt("iris.txt")

array([[           nan,            nan,            nan,            nan],
       [5.10156250e+00, 3.50000000e+00, 1.40039062e+00, 1.99951172e-01],
       [4.89843750e+00, 3.00000000e+00, 1.40039062e+00, 1.99951172e-01],
       [4.69921875e+00, 3.19921875e+00, 1.29980469e+00, 1.99951172e-01],
       [4.60156250e+00, 3.09960938e+00, 1.50000000e+00, 1.02031250e+01],
       [5.00000000e+01, 3.59960938e+00, 1.40039062e+00, 1.99951172e-01],
       [5.39843750e+00,            nan, 1.70019531e+00, 3.99902344e-01],
       [4.60156250e+00, 3.40039062e+00, 1.40039062e+00, 3.00048828e-01],
       [5.00000000e+00, 3.40039062e+00, 1.50000000e+00, 1.99951172e-01],
       [4.39843750e+00, 2.90039062e+00, 1.40039062e+00, 1.99951172e-01],
       [4.89843750e+00, 3.09960938e+00,            nan, 9.99755859e-02],
       [5.39843750e+00, 3.69921875e+00, 1.50000000e+00, 1.99951172e-01],
       [4.80078125e+00, 3.40039062e+00, 1.59960938e+00, 1.99951172e-01],
       [4.80078125e+00, 1.30000000e+02, 1.40039062e

In [7]:
sep_len = s2[0:,0]
sep_len

array([  nan,   5.1,   4.9,   4.7,   4.6,  50. ,   5.4,   4.6,   5. ,
         4.4,   4.9,   5.4,   4.8,   4.8,   4.3,   5.8,   5.7,  50.4,
         5.1,   5.7,   5.1,   5.4,   5.1,   4.6,   5.1,   4.8,   5. ,
         5. ,   5.2,   5.2,   4.7,   4.8,   5.4,   5.2,   5.5,   4.9,
         5. ,   5.5,   4.9,   4.4,   5.1,   5. ,   4.5,   4.4,   5. ,
         5.1,   4.8,   5.1,   4.6,   5.3,   5. ,   7. ,   6.4,   6.9,
         5.5,   6.5,   5.7, 116.3,   4.9,   6.6,   5.2,   5. ,   5.9,
         6. ,   6.1,   5.6,   6.7,   5.6,   5.8,   6.2,   5.6,   5.9,
         6.1,   6.3,   6.1,   6.4,   6.6,   6.8,   6.7,   6. ,   5.7,
         5.5,   5.5,   5.8,   6. ,   5.4,   6. ,   6.7,   6.3,   5.6,
         5.5,   5.5,   6.1,   5.8,   5. ,   5.6,   5.7,   5.7,   6.2,
         5.1,   5.7,   6.3,   5.8,   7.1,   6.3,   6.5,   7.6,   4.9,
         7.3,   6.7,   7.2,   6.5,   6.4,   6.8,   5.7,   5.8,   6.4,
         6.5,   7.7,   7.7,   6. ,   6.9,   5.6,   7.7,   6.3,   6.7,
         7.2,   6.2,

In [8]:
a1 = sep_len[sep_len > 6.0]
a1

array([ 50. ,  50.4,   7. ,   6.4,   6.9,   6.5, 116.3,   6.6,   6.1,
         6.7,   6.2,   6.1,   6.3,   6.1,   6.4,   6.6,   6.8,   6.7,
         6.7,   6.3,   6.1,   6.2,   6.3,   7.1,   6.3,   6.5,   7.6,
         7.3,   6.7,   7.2,   6.5,   6.4,   6.8,   6.4,   6.5,   7.7,
         7.7,   6.9,   7.7,   6.3,   6.7,   7.2,   6.2,   6.1,   6.4,
        70.2,   6.4,   6.3,   6.1,   7.7,   6.3,   6.4,   6.9,   6.7,
         6.9,   6.8,   6.7,   6.7,   6.3,   6.5,   6.2,   7.7,   7.2,
         7.3,   6.7,   7.7,   6.3,   7.2,   6.5,   6.4], dtype=float16)

In [9]:
b1 = sep_len[sep_len < 2.3]
b1

array([], dtype=float16)

In [10]:
median1 = np.nanmedian(sep_len)
median1

5.8

In [38]:
v = np.where(np.isnan(sep_len),median1,sep_len)
v

array([  5.8,   5.1,   4.9,   4.7,   4.6,  50. ,   5.4,   4.6,   5. ,
         4.4,   4.9,   5.4,   4.8,   4.8,   4.3,   5.8,   5.7,  50.4,
         5.1,   5.7,   5.1,   5.4,   5.1,   4.6,   5.1,   4.8,   5. ,
         5. ,   5.2,   5.2,   4.7,   4.8,   5.4,   5.2,   5.5,   4.9,
         5. ,   5.5,   4.9,   4.4,   5.1,   5. ,   4.5,   4.4,   5. ,
         5.1,   4.8,   5.1,   4.6,   5.3,   5. ,   7. ,   6.4,   6.9,
         5.5,   6.5,   5.7, 116.3,   4.9,   6.6,   5.2,   5. ,   5.9,
         6. ,   6.1,   5.6,   6.7,   5.6,   5.8,   6.2,   5.6,   5.9,
         6.1,   6.3,   6.1,   6.4,   6.6,   6.8,   6.7,   6. ,   5.7,
         5.5,   5.5,   5.8,   6. ,   5.4,   6. ,   6.7,   6.3,   5.6,
         5.5,   5.5,   6.1,   5.8,   5. ,   5.6,   5.7,   5.7,   6.2,
         5.1,   5.7,   6.3,   5.8,   7.1,   6.3,   6.5,   7.6,   4.9,
         7.3,   6.7,   7.2,   6.5,   6.4,   6.8,   5.7,   5.8,   6.4,
         6.5,   7.7,   7.7,   6. ,   6.9,   5.6,   7.7,   6.3,   6.7,
         7.2,   6.2,

In [40]:
sepallength = np.where(sep_len > 6.0,median1,v)
sepallength

array([5.8, 5.1, 4.9, 4.7, 4.6, 5.8, 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8,
       4.8, 4.3, 5.8, 5.7, 5.8, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8,
       5. , 5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9,
       4.4, 5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 5.8,
       5.8, 5.8, 5.5, 5.8, 5.7, 5.8, 4.9, 5.8, 5.2, 5. , 5.9, 6. , 5.8,
       5.6, 5.8, 5.6, 5.8, 5.8, 5.6, 5.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 5.8, 5.8, 5.6, 5.5,
       5.5, 5.8, 5.8, 5. , 5.6, 5.7, 5.7, 5.8, 5.1, 5.7, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 4.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.7, 5.8, 5.8,
       5.8, 5.8, 5.8, 6. , 5.8, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 6. , 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.9, 5.6, 5.8, 5.8, 5.8, 5.8,
       4.9, 5.8, 5.8, 5.9, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8], dtype=float16)

In [13]:
sep_wid = s2[0:,1]
sep_wid

array([  nan,   3.5,   3. ,   3.2,   3.1,   3.6,   nan,   3.4,   3.4,
         2.9,   3.1,   3.7,   3.4, 130. ,   3. ,   4. ,   4.4,   nan,
         3.5,   3.8,   3.8,   3.4,   3.7,   3.6,   3.3,   3.4,   3. ,
        34. ,   3.5,   3.4,   3.2,   3.1,   3.4,   4.1,   4.2,   3.1,
         3.2,   3.5,   3.1,   3. ,   3.4,   3.5,   2.3,   3.2,   3.5,
         3.8,   3. ,   3.8,   3.2,   3.7,   3.3,   3.2,   3.2,   nan,
         2.3,   2.8,   2.8,   3.3,   2.4,   2.9,   2.7,   2. ,   3. ,
         2.2,   2.9,   2.9,   3.1,   3. ,   2.7,   2.2,   2.5,   3.2,
         2.8,   2.5,   nan,   2.9,   3. ,   2.8,   3. ,   2.9,   2.6,
         2.4,   2.4,   2.7,   2.7,   3. ,   3.4,   3.1,   2.3,   3. ,
         2.5,   2.6,   3. , 112.6,   2.3,   2.7,   3. ,   2.9,   2.9,
         2.5,   2.8,   3.3,   2.7,   3. ,   2.9,   3. ,   3. ,   2.5,
         2.9,   2.5,   3.6,   3.2,   2.7,   3. ,   2.5,   2.8,   3.2,
         3. ,   3.8,   2.6,   2.2,   3.2,   2.8,   2.8,   2.7,   3.3,
         3.2,   2.8,

In [14]:
a2 = sep_wid[sep_wid > 3.4]
a2

array([  3.5,   3.6,   3.7, 130. ,   4. ,   4.4,   3.5,   3.8,   3.8,
         3.7,   3.6,  34. ,   3.5,   4.1,   4.2,   3.5,   3.5,   3.5,
         3.8,   3.8,   3.7, 112.6,   3.6,   3.8,   3.8,   3.6],
      dtype=float16)

In [15]:
b2 = sep_wid[sep_wid < 2.3]
b2

array([2. , 2.2, 2.2, 2.2], dtype=float16)

In [16]:
median2 = np.nanmedian(sep_wid)
median2

3.0

In [17]:
var = np.where(np.isnan(sep_wid),median2,sep_wid)
var

array([  3. ,   3.5,   3. ,   3.2,   3.1,   3.6,   3. ,   3.4,   3.4,
         2.9,   3.1,   3.7,   3.4, 130. ,   3. ,   4. ,   4.4,   3. ,
         3.5,   3.8,   3.8,   3.4,   3.7,   3.6,   3.3,   3.4,   3. ,
        34. ,   3.5,   3.4,   3.2,   3.1,   3.4,   4.1,   4.2,   3.1,
         3.2,   3.5,   3.1,   3. ,   3.4,   3.5,   2.3,   3.2,   3.5,
         3.8,   3. ,   3.8,   3.2,   3.7,   3.3,   3.2,   3.2,   3. ,
         2.3,   2.8,   2.8,   3.3,   2.4,   2.9,   2.7,   2. ,   3. ,
         2.2,   2.9,   2.9,   3.1,   3. ,   2.7,   2.2,   2.5,   3.2,
         2.8,   2.5,   3. ,   2.9,   3. ,   2.8,   3. ,   2.9,   2.6,
         2.4,   2.4,   2.7,   2.7,   3. ,   3.4,   3.1,   2.3,   3. ,
         2.5,   2.6,   3. , 112.6,   2.3,   2.7,   3. ,   2.9,   2.9,
         2.5,   2.8,   3.3,   2.7,   3. ,   2.9,   3. ,   3. ,   2.5,
         2.9,   2.5,   3.6,   3.2,   2.7,   3. ,   2.5,   2.8,   3.2,
         3. ,   3.8,   2.6,   2.2,   3.2,   2.8,   2.8,   2.7,   3.3,
         3.2,   2.8,

In [18]:
out = sep_wid[(sep_wid < 2.3) | (sep_wid > 3.4)]
out

array([  3.5,   3.6,   3.7, 130. ,   4. ,   4.4,   3.5,   3.8,   3.8,
         3.7,   3.6,  34. ,   3.5,   4.1,   4.2,   3.5,   3.5,   3.5,
         3.8,   3.8,   3.7,   2. ,   2.2,   2.2, 112.6,   3.6,   3.8,
         2.2,   3.8,   3.6], dtype=float16)

In [46]:
sepalwidth = np.where((sep_wid < 2.3) | (sep_wid > 3.4),median2,var)
sepalwidth

array([3. , 3. , 3. , 3.2, 3.1, 3. , 3. , 3.4, 3.4, 2.9, 3.1, 3. , 3.4,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3.4, 3. , 3. , 3.3, 3.4,
       3. , 3. , 3. , 3.4, 3.2, 3.1, 3.4, 3. , 3. , 3.1, 3.2, 3. , 3.1,
       3. , 3.4, 3. , 2.3, 3.2, 3. , 3. , 3. , 3. , 3.2, 3. , 3.3, 3.2,
       3.2, 3. , 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 3. , 3. , 3. , 2.9,
       2.9, 3.1, 3. , 2.7, 3. , 2.5, 3.2, 2.8, 2.5, 3. , 2.9, 3. , 2.8,
       3. , 2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5,
       2.6, 3. , 3. , 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. ,
       2.9, 3. , 3. , 2.5, 2.9, 2.5, 3. , 3.2, 2.7, 3. , 2.5, 2.8, 3.2,
       3. , 3. , 2.6, 3. , 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8,
       3. , 2.8, 3. , 2.8, 2.8, 2.6, 3. , 3.4, 3. , 3. , 3.1, 3.1, 3.1,
       2.7, 3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. , 2.8, 2.8, 2.7, 3.3, 3.2,
       2.5, 2.9, 2.5, 3. , 2.8, 2.8, 2.7, 3. , 3.2, 2.7], dtype=float16)

In [20]:
pet_len = s2[0:,2]
pet_len

array([ nan,  1.4,  1.4,  1.3,  1.5,  1.4,  1.7,  1.4,  1.5,  1.4,  nan,
        1.5,  1.6,  1.4,  1.1,  1.2,  1.5,  1.3,  1.4,  1.7,  1.5,  1.7,
        1.5,  1. ,  1.7,  1.9,  1.6,  1.6,  1.5,  1.4,  1.6,  1.6,  1.5,
        1.5,  1.4,  1.5,  1.2,  1.3,  1.5,  1.3,  1.5,  1.3, 13. ,  1.3,
        1.6,  1.9,  1.4,  1.6,  1.4,  1.5,  1.4,  4.7,  4.5,  4.9,  4. ,
        4.6,  4.5,  4.7,  3.3,  4.6,  3.9,  3.5,  4.2,  4. ,  4.7,  3.6,
        4.4,  4.5,  4.1,  4.5,  3.9,  4.8,  4. ,  4.9,  4.7,  4.3,  4.4,
        4.8,  5. ,  4.5,  3.5, 13.8,  3.7,  3.9,  5.1,  4.5,  4.5,  4.7,
        4.4,  4.1,  4. ,  4.4,  nan,  4. ,  3.3,  4.2,  4.2,  4.2,  4.3,
        3. ,  4.1,  6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  4.5,  6.3,  5.8,
        6.1,  5.1,  5.3,  nan,  5. ,  5.1,  5.3,  5.5,  6.7,  6.9,  5. ,
        5.7,  4.9,  6.7,  4.9,  5.7,  6. ,  4.8,  4.9,  5.6,  5.8,  6.1,
        nan,  5.6,  5.1,  5.6,  6.1,  5.6,  5.5,  4.8,  5.4,  nan,  5.1,
        5.1,  5.9,  5.7,  nan,  5. ,  5.2,  5.4,  5

In [21]:
a3 = pet_len[pet_len < 1.0]
a3

array([], dtype=float16)

In [22]:
b3 = pet_len[pet_len > 6.9]
b3

array([13. , 13.8], dtype=float16)

In [23]:
out1 = pet_len[(pet_len < 1.0)| (pet_len > 6.9)]
out1

array([13. , 13.8], dtype=float16)

In [24]:
median3 = np.nanmedian(pet_len)
median3

4.5

In [25]:
var1 = np.where(np.isnan(pet_len),median3,pet_len)
var1

array([ 4.5,  1.4,  1.4,  1.3,  1.5,  1.4,  1.7,  1.4,  1.5,  1.4,  4.5,
        1.5,  1.6,  1.4,  1.1,  1.2,  1.5,  1.3,  1.4,  1.7,  1.5,  1.7,
        1.5,  1. ,  1.7,  1.9,  1.6,  1.6,  1.5,  1.4,  1.6,  1.6,  1.5,
        1.5,  1.4,  1.5,  1.2,  1.3,  1.5,  1.3,  1.5,  1.3, 13. ,  1.3,
        1.6,  1.9,  1.4,  1.6,  1.4,  1.5,  1.4,  4.7,  4.5,  4.9,  4. ,
        4.6,  4.5,  4.7,  3.3,  4.6,  3.9,  3.5,  4.2,  4. ,  4.7,  3.6,
        4.4,  4.5,  4.1,  4.5,  3.9,  4.8,  4. ,  4.9,  4.7,  4.3,  4.4,
        4.8,  5. ,  4.5,  3.5, 13.8,  3.7,  3.9,  5.1,  4.5,  4.5,  4.7,
        4.4,  4.1,  4. ,  4.4,  4.5,  4. ,  3.3,  4.2,  4.2,  4.2,  4.3,
        3. ,  4.1,  6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  4.5,  6.3,  5.8,
        6.1,  5.1,  5.3,  4.5,  5. ,  5.1,  5.3,  5.5,  6.7,  6.9,  5. ,
        5.7,  4.9,  6.7,  4.9,  5.7,  6. ,  4.8,  4.9,  5.6,  5.8,  6.1,
        4.5,  5.6,  5.1,  5.6,  6.1,  5.6,  5.5,  4.8,  5.4,  4.5,  5.1,
        5.1,  5.9,  5.7,  4.5,  5. ,  5.2,  5.4,  5

In [64]:
petallength = np.where((pet_len < 1.0)| (pet_len > 6.9),median3,var1)
petallength

array([4.5, 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 4.5, 1.5, 1.6,
       1.4, 1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9,
       1.6, 1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5,
       1.3, 1.5, 1.3, 4.5, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7,
       4.5, 4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7,
       3.6, 4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8,
       5. , 4.5, 3.5, 4.5, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. ,
       4.4, 4.5, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9,
       5.6, 5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 4.5, 5. , 5.1, 5.3,
       5.5, 6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6,
       5.8, 6.1, 4.5, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 4.5, 5.1,
       5.1, 5.9, 5.7, 4.5, 5. , 5.2, 5.4, 5.1, 4.9, 6.7, 4.9, 5.7, 6. ,
       4.5, 6.3, 5.8, 5.1, 4.9, 6.7, 4.9, 6.1, 5.1, 5.3], dtype=float16)

In [27]:
pet_wid = s2[0:,3]
pet_wid

array([      nan, 2.000e-01, 2.000e-01, 2.000e-01, 1.020e+01, 2.000e-01,
       3.999e-01, 3.000e-01, 2.000e-01, 2.000e-01, 9.998e-02, 2.000e-01,
       2.000e-01, 1.010e+01, 9.998e-02, 2.000e-01, 3.999e-01, 3.999e-01,
       3.000e-01, 3.000e-01, 3.000e-01, 2.000e-01, 3.999e-01, 2.000e-01,
       5.000e-01, 2.000e-01, 2.000e-01, 3.999e-01, 2.000e-01, 1.102e+02,
       2.000e-01, 2.000e-01, 3.999e-01, 9.998e-02, 2.000e-01, 9.998e-02,
       2.000e-01, 2.000e-01, 9.998e-02, 2.000e-01, 2.000e-01, 3.000e-01,
       3.000e-01, 2.000e-01, 6.001e-01, 3.999e-01, 3.000e-01, 2.000e-01,
       2.000e-01, 2.000e-01, 2.000e-01, 1.400e+00, 1.500e+00, 1.500e+00,
       1.300e+00, 1.500e+00, 1.300e+00, 1.600e+00, 1.600e+01, 1.300e+00,
       1.400e+00, 1.000e+00, 1.500e+00, 1.000e+00, 1.400e+00, 1.300e+00,
       1.400e+00, 1.500e+00, 1.000e+00, 1.500e+00, 1.100e+00, 1.800e+00,
       1.300e+00, 1.500e+00, 1.200e+00, 1.300e+00, 1.400e+00, 1.400e+00,
       1.700e+00, 1.500e+00, 1.000e+00, 1.100e+00, 

In [28]:
a4 = pet_wid[pet_wid < 2]
a4

array([0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2,
       0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2, 0.4, 0.2,
       0.2, 0.2, 0.4, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2, 0.2, 0.3, 0.3,
       0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5, 1.5, 1.3, 1.5,
       1.3, 1.6, 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3, 1.4, 1.5, 1. , 1.5,
       1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7, 1.5, 1. , 1.1, 1. ,
       1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2, 1.4, 1.2, 1. , 1.3,
       1.2, 1.3, 1.3, 1.3, 1.9, 1.8, 1.7, 1.8, 1.8, 1.9, 1.8, 1.5, 1.8,
       1.8, 1.8, 1.8, 1.6, 1.9, 1.5, 1.4, 1.8, 1.8, 1.9, 1.9, 1.8, 1.8,
       1.8, 1.7, 1.8, 1.8, 1.8, 1.8, 1.9], dtype=float16)

In [29]:
b4 = pet_wid[pet_wid > 3.5]
b4

array([ 10.2,  10.1, 110.2,  16. , 111.1], dtype=float16)

In [30]:
out2 = pet_wid[(pet_wid < 2)|(pet_wid > 3.5)]
out2

array([2.000e-01, 2.000e-01, 2.000e-01, 1.020e+01, 2.000e-01, 3.999e-01,
       3.000e-01, 2.000e-01, 2.000e-01, 9.998e-02, 2.000e-01, 2.000e-01,
       1.010e+01, 9.998e-02, 2.000e-01, 3.999e-01, 3.999e-01, 3.000e-01,
       3.000e-01, 3.000e-01, 2.000e-01, 3.999e-01, 2.000e-01, 5.000e-01,
       2.000e-01, 2.000e-01, 3.999e-01, 2.000e-01, 1.102e+02, 2.000e-01,
       2.000e-01, 3.999e-01, 9.998e-02, 2.000e-01, 9.998e-02, 2.000e-01,
       2.000e-01, 9.998e-02, 2.000e-01, 2.000e-01, 3.000e-01, 3.000e-01,
       2.000e-01, 6.001e-01, 3.999e-01, 3.000e-01, 2.000e-01, 2.000e-01,
       2.000e-01, 2.000e-01, 1.400e+00, 1.500e+00, 1.500e+00, 1.300e+00,
       1.500e+00, 1.300e+00, 1.600e+00, 1.600e+01, 1.300e+00, 1.400e+00,
       1.000e+00, 1.500e+00, 1.000e+00, 1.400e+00, 1.300e+00, 1.400e+00,
       1.500e+00, 1.000e+00, 1.500e+00, 1.100e+00, 1.800e+00, 1.300e+00,
       1.500e+00, 1.200e+00, 1.300e+00, 1.400e+00, 1.400e+00, 1.700e+00,
       1.500e+00, 1.000e+00, 1.100e+00, 1.000e+00, 

In [31]:
median4 = np.nanmedian(pet_wid)
median4

1.5

In [32]:
var3 = np.where(np.isnan(pet_wid),median4,pet_wid)
var3

array([1.500e+00, 2.000e-01, 2.000e-01, 2.000e-01, 1.020e+01, 2.000e-01,
       3.999e-01, 3.000e-01, 2.000e-01, 2.000e-01, 9.998e-02, 2.000e-01,
       2.000e-01, 1.010e+01, 9.998e-02, 2.000e-01, 3.999e-01, 3.999e-01,
       3.000e-01, 3.000e-01, 3.000e-01, 2.000e-01, 3.999e-01, 2.000e-01,
       5.000e-01, 2.000e-01, 2.000e-01, 3.999e-01, 2.000e-01, 1.102e+02,
       2.000e-01, 2.000e-01, 3.999e-01, 9.998e-02, 2.000e-01, 9.998e-02,
       2.000e-01, 2.000e-01, 9.998e-02, 2.000e-01, 2.000e-01, 3.000e-01,
       3.000e-01, 2.000e-01, 6.001e-01, 3.999e-01, 3.000e-01, 2.000e-01,
       2.000e-01, 2.000e-01, 2.000e-01, 1.400e+00, 1.500e+00, 1.500e+00,
       1.300e+00, 1.500e+00, 1.300e+00, 1.600e+00, 1.600e+01, 1.300e+00,
       1.400e+00, 1.000e+00, 1.500e+00, 1.000e+00, 1.400e+00, 1.300e+00,
       1.400e+00, 1.500e+00, 1.000e+00, 1.500e+00, 1.100e+00, 1.800e+00,
       1.300e+00, 1.500e+00, 1.200e+00, 1.300e+00, 1.400e+00, 1.400e+00,
       1.700e+00, 1.500e+00, 1.000e+00, 1.100e+00, 

In [65]:
petalwidth = np.where((pet_wid < 2)|(pet_wid > 3.5),median4,var3)
petalwidth

array([1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5,
       1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5,
       1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5,
       1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5,
       1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5,
       1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5,
       1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5,
       1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 2.5, 1.5, 2.1,
       1.5, 2.2, 2.1, 1.5, 1.5, 1.5, 2.5, 2. , 1.5, 2.1, 2. , 2.4, 2.3,
       1.5, 2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.5, 2.1, 1.5, 1.5, 1.5, 2.1,
       1.5, 1.5, 2. , 2.2, 1.5, 1.5, 2.3, 2.4, 1.5, 1.5, 2.1, 2.4, 2.3,
       1.5, 2.3, 2.5, 2.3, 1.5, 2. , 2.3, 1.5, 2. , 2. , 1.5, 2.1, 1.5,
       1.5, 1.5, 1.5, 1.5, 2. , 2. , 1.5, 2.5, 2. , 1.5], dtype=float16)

# What is the mean value of sepal length

In [42]:
sepallength.dtype = 'float16'

In [45]:
np.mean(sepallength)

5.52

# 3.sort the sepal width in ascending order.

In [47]:
np.sort(sepalwidth)

array([2.3, 2.3, 2.3, 2.3, 2.4, 2.4, 2.4, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5,
       2.5, 2.5, 2.5, 2.5, 2.6, 2.6, 2.6, 2.6, 2.7, 2.7, 2.7, 2.7, 2.7,
       2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8,
       2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.9, 2.9,
       2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1,
       3.1, 3.1, 3.1, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2,
       3.2, 3.2, 3.2, 3.2, 3.2, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.4,
       3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4], dtype=float16)

# 4.apply all statistical measures on sepal width and length

In [48]:
np.mean(sepalwidth)

2.947

In [49]:
np.median(sepalwidth)

3.0

In [50]:
np.min(sepalwidth)

2.3

In [51]:
np.max(sepalwidth)

3.4

In [53]:
range1 = np.max(sepalwidth) - np.min(sepalwidth)
range1

1.1

In [54]:
np.var(sepalwidth)

0.0643

In [55]:
np.std(sepalwidth)

0.2534

In [56]:
np.mean(sepallength)

5.52

In [57]:
np.median(sepallength)

5.8

In [58]:
np.max(sepallength)

6.0

In [59]:
np.min(sepallength)

4.3

In [61]:
range2 = np.max(sepallength) - np.min(sepallength)
range2

1.699

In [62]:
np.var(sepallength)

0.1782

In [63]:
np.std(sepallength)

0.422

# 5.after cleaning the data ,save the file as 'cleaned_iris.txt' and load to jupyter again to display the values
​

In [68]:
f = np.hstack((sepallength,sepalwidth))
f

array([5.8, 5.1, 4.9, 4.7, 4.6, 5.8, 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8,
       4.8, 4.3, 5.8, 5.7, 5.8, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8,
       5. , 5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9,
       4.4, 5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 5.8,
       5.8, 5.8, 5.5, 5.8, 5.7, 5.8, 4.9, 5.8, 5.2, 5. , 5.9, 6. , 5.8,
       5.6, 5.8, 5.6, 5.8, 5.8, 5.6, 5.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 5.8, 5.8, 5.6, 5.5,
       5.5, 5.8, 5.8, 5. , 5.6, 5.7, 5.7, 5.8, 5.1, 5.7, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 4.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.7, 5.8, 5.8,
       5.8, 5.8, 5.8, 6. , 5.8, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 6. , 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.9, 5.6, 5.8, 5.8, 5.8, 5.8,
       4.9, 5.8, 5.8, 5.9, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8, 3. , 3. , 3. ,
       3.2, 3.1, 3. , 3. , 3.4, 3.4, 2.9, 3.1, 3. , 3.4, 3. , 3.

In [70]:
f2 = np.hstack((petallength,petalwidth))
f2

array([4.5, 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 4.5, 1.5, 1.6,
       1.4, 1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9,
       1.6, 1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5,
       1.3, 1.5, 1.3, 4.5, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7,
       4.5, 4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7,
       3.6, 4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8,
       5. , 4.5, 3.5, 4.5, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. ,
       4.4, 4.5, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9,
       5.6, 5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 4.5, 5. , 5.1, 5.3,
       5.5, 6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6,
       5.8, 6.1, 4.5, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 4.5, 5.1,
       5.1, 5.9, 5.7, 4.5, 5. , 5.2, 5.4, 5.1, 4.9, 6.7, 4.9, 5.7, 6. ,
       4.5, 6.3, 5.8, 5.1, 4.9, 6.7, 4.9, 6.1, 5.1, 5.3, 1.5, 1.5, 1.5,
       1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.

In [86]:
flower = np.hstack((f,f2))
iris = flower.astype('int16')
iris

array([5, 5, 4, 4, 4, 5, 5, 4, 5, 4, 4, 5, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5,
       5, 4, 5, 4, 5, 5, 5, 5, 4, 4, 5, 5, 5, 4, 5, 5, 4, 4, 5, 5, 4, 4,
       5, 5, 4, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 6, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 6, 5, 6, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       2, 2, 2, 3, 2, 2, 2, 3, 3, 3, 2, 2, 3, 3, 2, 3, 2, 3, 2, 2, 3, 2,
       3, 2, 3, 2, 2, 2, 2, 2, 2, 3, 3, 3, 2, 3, 2, 2, 3, 3, 2, 2, 3, 2,
       2, 2, 2, 3, 2, 3, 2, 3, 3, 2, 2, 2, 3, 3, 2, 3, 2, 2, 3, 3, 3, 2,
       3, 3, 2, 2, 2, 3, 3, 2, 3, 2, 3, 2, 3, 2, 2,

In [87]:
np.savetxt('cleaned_iris.txt',iris)

In [88]:
np.loadtxt('cleaned_iris.txt')

array([5., 5., 4., 4., 4., 5., 5., 4., 5., 4., 4., 5., 4., 4., 4., 5., 5.,
       5., 5., 5., 5., 5., 5., 4., 5., 4., 5., 5., 5., 5., 4., 4., 5., 5.,
       5., 4., 5., 5., 4., 4., 5., 5., 4., 4., 5., 5., 4., 5., 4., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 4., 5., 5., 5., 5., 6., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 6., 5., 5., 5., 5., 6.,
       5., 6., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 4., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 6., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 6., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 4., 5., 5., 5., 5., 5., 5., 5., 5., 5., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 2., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 2., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 2.,
       2., 2., 3., 2., 2.

In [89]:
np.savez('cleaned_iris.npz',sepallength,sepalwidth,petallength,petalwidth)

In [90]:
np.load('cleaned_iris.npz')

NpzFile 'cleaned_iris.npz' with keys: arr_0, arr_1, arr_2, arr_3